drop table if exists  CAST_VIEW;

CREATE TABLE CAST_VIEW

(             

cast_id                                     NUMBER(9) NOT NULL ,

role_id                                       NUMBER(9) NOT NULL ,

rolename                                      VARCHAR2(30 CHAR) NOT NULL ,

cast_order                                  NUMBER(3) NOT NULL ,

firstname                                     VARCHAR2(20 CHAR) NOT NULL ,

lastname                                      VARCHAR2(20 CHAR) NOT NULL ,

object_id                                   NUMBER(9) NOT NULL

);

Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (7238,7819,'Star',2,'Pete','Postlethwaite',5864);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (8773,7819,'Star',4,'Tara','Fitzgerald',5864);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (16069,7818,'Director',1,'Mark','Herman',5864);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (16786,7819,'Star',3,'Ewan','Mcgregor',5864);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (1234,7819,'Star',1,'Michael','Keaton',5885);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (3623,7819,'Star',2,'Andy','Garcia',5885);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (4067,7818,'Director',3,'Barbet','Schroeder',5885);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (5557,7819,'Star',1,'Brad','Pitt',5899);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (8239,7819,'Star',2,'David','Thewlis',5899);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (16945,7818,'Director',3,'Jean-Jacques','Annaud',5899);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (14183,7819,'Star',3,'Natalie','Desselle',6127);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (14188,7819,'Star',2,'Bill','Bellamy',6127);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (16424,7819,'Star',4,'Lark','Voorlies',6127);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (16425,7818,'Director',1,'Lionel.C.','Martin',6127);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (1086,7818,'Director',1,'Lawrence','Kasdan',6770);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (1241,7819,'Star',5,'Brian','Dennehy',6770);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (1425,7819,'Star',6,'Kevin','Costner',6770);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (1573,7819,'Star',7,'Danny','Glover',6770);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (1864,7819,'Star',4,'John','Cleese',6770);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (2344,7819,'Star',2,'Scott','Glenn',6770);
Insert into CAST_VIEW (CAST_ID,ROLE_ID,ROLENAME,CAST_ORDER,FIRSTNAME,LASTNAME,OBJECT_ID) values (3536,7819,'Star',3,'Kevin','Kline',6770);
